# Generated by Django 5.1.6 on 2025-03-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='students_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fan',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.CharField(max_length=255),
        ),
    ]
